Repository PiotrKolecki/team-programming-game-shop, pull requests merged in 2021-05, with the labels that each got.

#25 Feat/store view
  frontend/src/assets/witcher.png
  frontend/src/components/GameCard/GameCard.tsx
  frontend/src/components/Sidebar/Sidebar.tsx
  frontend/src/constants/theme.ts
  frontend/src/domain/Home/Catalogue/Catalogue.tsx
  frontend/src/domain/Home/Home.tsx
Labels: enhancement

#29 Order management service
  README.md
  order-management-service/order-management-client/pom.xml
  order-management-service/order-management-client/src/main/resources/api.yaml
  order-management-service/order-management-server/Dockerfile
  order-management-service/order-management-server/k8s/deployment-local.yaml
  order-management-service/order-management-server/k8s/deployment.yaml
  order-management-service/order-management-server/pom.xml
  order-management-service/order-management-server/src/main/java/agh/fis/order_management/OrderManagementApplication.java
  order-management-service/order-management-server/src/main/java/agh/fis/order_management/controller/OrderManagementController.java
  order-management-service/order-management-server/src/main/java/agh/fis/order_management/model/ItemEntity.java
  order-management-service/order-management-server/src/main/java/agh/fis/order_management/model/OrderEntity.java
  order-management-service/order-management-server/src/main/java/agh/fis/order_management/repository/OrderRepository.java
  order-management-service/order-management-server/src/main/java/agh/fis/order_management/service/OrderService.java
  order-management-service/order-management-server/src/main/resources/application.properties
  order-management-service/pom.xml
  order-management-service/src/main/java/agh/fis/order_management/controller/OrderManagementController.java
  order-management-service/src/main/resources/application.properties
Labels: enhancement

#33 fix https and Procfile for heroku
  api-documentation/Procfile
  api-documentation/src/main/resources/application.yml
  common/src/main/java/agh/fis/common/filter/CorsFilter.java
Labels: Fix

#35 fixed path to docker file
  .github/workflows/google.yml
  README.md
Labels: Fix, bug

#36 rmeove https in swagger baseurl
  api-documentation/src/main/resources/application.yml
Labels: Fix, bug

#18 Profile, orders pages and footer
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/src/App.tsx
  frontend/src/assets/arrow.svg
  frontend/src/assets/user.svg
  frontend/src/components/Footer/Footer.tsx
  frontend/src/components/Footer/parts.ts
  frontend/src/components/Logo/Logo.tsx
  frontend/src/components/MainWrapper/MainWrapper.tsx
  frontend/src/components/MainWrapper/parts.ts
  frontend/src/components/Masthead/Masthead.tsx
  frontend/src/domain/Account/AccountWrapper/AccountWrapper.tsx
  frontend/src/domain/Account/AccountWrapper/parts.ts
  frontend/src/domain/Account/Navigation/Navigation.tsx
  frontend/src/domain/Account/Navigation/parts.ts
  frontend/src/domain/Account/Orders/Order/AdditionalCosts.tsx
  frontend/src/domain/Account/Orders/Order/Order.tsx
  frontend/src/domain/Account/Orders/Order/Trigger/Trigger.tsx
  frontend/src/domain/Account/Orders/Order/Trigger/parts.ts
  frontend/src/domain/Account/Orders/Order/parts.ts
  frontend/src/domain/Account/Orders/Orders.tsx
  frontend/src/domain/Account/Orders/parts.ts
  frontend/src/domain/Account/PersonalData/PersonalData.tsx
  frontend/src/domain/Account/PersonalData/helpers.ts
  frontend/src/domain/Account/PersonalData/parts.ts
  frontend/src/domain/Account/PersonalData/validators.ts
Labels: enhancement

#43 build test pr init
  .github/workflows/buildTestPR.yml
Labels: High Priority, enhancement

#44 Basic implementation of order creation
  order-management-service/order-management-client/src/main/resources/api.yaml
  order-management-service/order-management-server/src/main/java/agh/fis/order_management/component/IOrderMapper.java
  order-management-service/order-management-server/src/main/java/agh/fis/order_management/component/OrderMapper.java
  order-management-service/order-management-server/src/main/java/agh/fis/order_management/controller/OrderManagementController.java
  order-management-service/order-management-server/src/main/java/agh/fis/order_management/model/AddressEntity.java
  order-management-service/order-management-server/src/main/java/agh/fis/order_management/model/DeliveryEntity.java
  order-management-service/order-management-server/src/main/java/agh/fis/order_management/model/ItemEntity.java
  order-management-service/order-management-server/src/main/java/agh/fis/order_management/model/OrderEntity.java
  order-management-service/order-management-server/src/main/java/agh/fis/order_management/repository/OrderRepository.java
  order-management-service/order-management-server/src/main/java/agh/fis/order_management/service/OrderService.java
Labels: enhancement

#47 fix username for api-key deploy
  .github/workflows/Heroku.yml
Labels: Fix, High Priority, bug

#41 Payment management CRUD implementation
  .github/workflows/buildTestPR.yml
  .github/workflows/google.yml
  .gitignore
  README.md
  payment-management-service/payment-management-client/pom.xml
  payment-management-service/payment-management-client/src/main/resources/api.yaml
  payment-management-service/payment-management-server/Dockerfile
  payment-management-service/payment-management-server/k8s/deployment-local.yaml
  payment-management-service/payment-management-server/k8s/deployment.yaml
  payment-management-service/payment-management-server/pom.xml
  payment-management-service/payment-management-server/src/main/java/agh/fis/payment_management/PaymentManagementApplication.java
  payment-management-service/payment-management-server/src/main/java/agh/fis/payment_management/controller/PaymentManagementController.java
  payment-management-service/payment-management-server/src/main/java/agh/fis/payment_management/model/PaymentEntity.java
  payment-management-service/payment-management-server/src/main/java/agh/fis/payment_management/repository/PaymentRepository.java
  payment-management-service/payment-management-server/src/main/java/agh/fis/payment_management/service/PaymentService.java
  payment-management-service/pom.xml
  payment-management-service/src/main/java/agh/fis/payment_management/controller/PaymentManagementController.java
  payment-management-service/src/main/resources/application.properties
Labels: enhancement

#34 Feat/single game view
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/assets/gta.png
  frontend/src/components/GameCard/GameCard.tsx
  frontend/src/components/Input/Input.tsx
  frontend/src/components/Masthead/Navigation.tsx
  frontend/src/components/Masthead/Search.tsx
  frontend/src/components/Sidebar/Sidebar.tsx
  frontend/src/config.ts
  frontend/src/constants/theme.ts
  frontend/src/domain/Catalogue/Catalogue.tsx
  frontend/src/domain/Catalogue/index.ts
  frontend/src/domain/Home/Catalogue/Catalogue.tsx
  frontend/src/domain/Home/Home.tsx
  frontend/src/domain/SingleGame/SingleGame.tsx
  frontend/src/domain/SingleGame/index.tsx
  frontend/src/domain/WeclomeScreen/Form/Form.tsx
  frontend/src/domain/index.ts
  frontend/src/services/client/index.ts
  frontend/src/store/catalogue/index.ts
  frontend/src/store/catalogue/sagas.ts
  frontend/src/store/catalogue/selectors.ts
  frontend/src/store/catalogue/types.ts
  frontend/src/store/index.ts
  frontend/src/store/rootReducer.ts
  frontend/src/store/rootSaga.ts
Labels: enhancement
