Repository PiotrKolecki/team-programming-game-shop, pull requests merged in 2021-06, with the labels that each got.

#51 Order management service/feign communication with payment management
  order-management-service/order-management-client/src/main/resources/api.yaml
  order-management-service/order-management-server/pom.xml
  order-management-service/order-management-server/src/main/java/agh/fis/order_management/client/PaymentManagementClient.java
  order-management-service/order-management-server/src/main/java/agh/fis/order_management/client/ProductCatalogClient.java
  order-management-service/order-management-server/src/main/java/agh/fis/order_management/component/AuthenticationHelper.java
  order-management-service/order-management-server/src/main/java/agh/fis/order_management/component/IAuthenticationHelper.java
  order-management-service/order-management-server/src/main/java/agh/fis/order_management/component/IPriceCalculator.java
  order-management-service/order-management-server/src/main/java/agh/fis/order_management/component/OrderMapper.java
  order-management-service/order-management-server/src/main/java/agh/fis/order_management/component/PriceCalculator.java
  order-management-service/order-management-server/src/main/java/agh/fis/order_management/controller/OrderManagementController.java
  order-management-service/order-management-server/src/main/java/agh/fis/order_management/repository/OrderRepository.java
  order-management-service/order-management-server/src/main/java/agh/fis/order_management/service/OrderService.java
Labels: enhancement

#52 Implemented communication with Order Management
  payment-management-service/payment-management-client/src/main/resources/api.yaml
  payment-management-service/payment-management-server/pom.xml
  payment-management-service/payment-management-server/src/main/java/agh/fis/payment_management/client/OrderManagementClient.java
  payment-management-service/payment-management-server/src/main/java/agh/fis/payment_management/controller/PaymentManagementController.java
  payment-management-service/payment-management-server/src/main/java/agh/fis/payment_management/service/PaymentService.java
Labels: enhancement

#46 Working get all endpoint with example data
  log.txt
  product-catalog-service/pom.xml
  product-catalog-service/src/main/java/agh/fis/product_catalog/controller/ProductCatalogController.java
  product-catalog-service/src/main/java/agh/fis/product_catalog/model/Product.java
  product-catalog-service/src/main/java/agh/fis/product_catalog/model/ProductBaseEntity.java
  product-catalog-service/src/main/java/agh/fis/product_catalog/repository/ProductRepository.java
  product-catalog-service/src/main/java/agh/fis/product_catalog/service/ProductService.java
  product-catalog-service/src/main/resources/api.yaml
  product-catalog-service/src/main/resources/application.properties
Labels: High Priority, enhancement

#58 order price calculated based on product catalog
  order-management-service/order-management-server/src/main/java/agh/fis/order_management/client/ProductCatalogClient.java
  order-management-service/order-management-server/src/main/java/agh/fis/order_management/component/AuthenticationHelper.java
  order-management-service/order-management-server/src/main/java/agh/fis/order_management/component/IPriceCalculator.java
  order-management-service/order-management-server/src/main/java/agh/fis/order_management/component/PriceCalculator.java
  order-management-service/order-management-server/src/main/java/agh/fis/order_management/model/ProductDto.java
  order-management-service/order-management-server/src/main/java/agh/fis/order_management/service/OrderService.java
Labels: enhancement

#57 fix user logout after page reload
  frontend/src/App.tsx
  frontend/src/store/user/actionTypes.ts
  frontend/src/store/user/actions.ts
  frontend/src/store/user/reducer.ts
  frontend/src/store/user/sagas.ts
  frontend/src/store/user/types.ts
Labels: bug

#59 Feat/shopping cart logic
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/assets/Rectangle 4.png
  frontend/src/components/Alert/Alert.tsx
  frontend/src/components/GameCard/GameCard.tsx
  frontend/src/components/Masthead/Navigation.tsx
  frontend/src/domain/Account/Cart/Cart.tsx
  frontend/src/domain/Account/Cart/Delivery/Delivery.tsx
  frontend/src/domain/Account/Cart/Delivery/DeliveryForms/RecipientForm.tsx
  frontend/src/domain/Account/Cart/ProductsList/CartProduct/CartProduct.tsx
  frontend/src/domain/Account/Orders/Order/Order.tsx
  frontend/src/domain/Catalogue/Catalogue.tsx
  frontend/src/domain/SingleGame/SingleGame.tsx
  frontend/src/services/client/index.ts
  frontend/src/store/cart/index.ts
  frontend/src/store/cart/sagas.ts
  frontend/src/store/cart/selectors.ts
  frontend/src/store/cart/types.ts
  frontend/src/store/catalogue/index.ts
  frontend/src/store/catalogue/sagas.ts
  frontend/src/store/catalogue/selectors.ts
  frontend/src/store/catalogue/types.ts
  frontend/src/store/orders/selectors.ts
  frontend/src/store/orders/types.ts
  frontend/src/store/rootReducer.ts
  frontend/src/store/rootSaga.ts
Labels: enhancement
